# Generated by Django 2.2.6 on 2019-11-09 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('canSave', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('private', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
                ('creators', models.ManyToManyField(related_name='creators', to='paint.Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixels', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('edited', models.ManyToManyField(related_name='edited_pictures', to='paint.Picture')),
                ('favourited', models.ManyToManyField(related_name='favourited_pictures', to='paint.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=50)),
                ('layerNumber', models.IntegerField(default=0)),
                ('partOfPicture', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='paint.Picture')),
                ('strips', models.ManyToManyField(related_name='strips', to='paint.Picture')),
            ],
        ),
    ]
