# Generated by Django 2.2.6 on 2019-11-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='partOfPicture',
        ),
        migrations.AddField(
            model_name='picture',
            name='layers',
            field=models.ManyToManyField(related_name='layers', to='paint.Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='strips',
            field=models.ManyToManyField(related_name='strips', to='paint.Strip'),
        ),
    ]
