# Generated by Django 2.2.6 on 2019-11-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0002_auto_20191108_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='strips',
        ),
        migrations.AddField(
            model_name='layer',
            name='url',
            field=models.CharField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='picture',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
