# Generated by Django 2.2.6 on 2019-11-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0003_auto_20191118_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='othersCanEdit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='layer',
            name='url',
            field=models.URLField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='picture',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
