# Generated by Django 2.2.6 on 2019-11-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0004_auto_20191121_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='name',
        ),
    ]
