# Generated by Django 2.2.6 on 2019-11-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0007_picture_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strip',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='creators',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='height',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='password',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='width',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
