# Generated by Django 2.2.6 on 2019-12-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0008_auto_20191127_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='url',
            field=models.URLField(default='', max_length=10485760),
        ),
    ]
