# Generated by Django 2.2.6 on 2019-12-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0009_auto_20191201_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
